version: '3'

services:
  php:
    container_name: php
    build: ./php
    volumes:
    - ./www:/var/www

  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 8080:80
    volumes:
    - ./www:/var/www
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atago_system
      MYSQL_USER: atago
      MYSQL_PASSWORD: atago
      TZ: 'Asia/Tokyo'
    volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
    - 3306:3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=mysql
    - PMA_USER=root
    - PMA_PASSWORD=root
    ports:
    - 18080:80